---
# MySQL setings
mysql_root_password: "rootpassword"
mysql_db: "wordpress"
mysql_user: "wordpress"
mysql_password: "password"

#HTTP setings
http_host: "hostname"
http_conf: "wordpress.conf"
http_port: "80"
